name: GitHub Actions Demo
on:
  workflow_dispatch:
  schedule:
    - cron: "* * * * *"
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v6
      - run: python python_job.py
      - run: echo "coucou" > result.txt
      - name: Upload result.txt as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: upload-my-result
          path: result.txt
      - run: env
        env:
          super_secret: ${{ secrets.SECRET_API_KEY }}
      - run: python python_job.py
        env:
          super_secret: ${{ secrets.SECRET_API_KEY }}
